<h2><span style="color:red">🚨 Run the below cell to install and import required packages</span></h2>


In [1]:
!pip install numpy_assignment_tests-0.1-py3-none-any.whl --force-reinstall
import numpy as np

Processing c:\users\dell\onedrive\desktop\suretrust\18-04 classtest_numpy_operations\numpy_assignment_tests-0.1-py3-none-any.whl


## 📝 **18th April NumPy Class Test - 45 Minute Duration**

---

### ✅ **Problem 1: Array Creation and Basic Operations**

**Steps to solve:**

1. Create a NumPy array of even numbers from 10 to 50 (inclusive).
2. Multiply all elements of the array by 2 and store it in a new variable.
3. Compute the sum of all elements in the doubled array.
4. Reshape the doubled array into a 2D array with 5 rows and 4 columns.

**Function Signature:**

In [24]:
def problem1():
    arr = np.arange(10, 51, 2)  

    arr_doubled = arr * 2

    total = np.sum(arr_doubled)

    reshaped = arr_doubled[:20].reshape(5, 4)

    return arr_doubled, total, reshaped

In [25]:
doubled, total, reshaped = problem1()

print("Original array:", arr)
print("Doubled array:", doubled)
print("Sum of doubled array:", total)
print("Reshaped array:\n", reshaped)


Original array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Doubled array: [ 20  24  28  32  36  40  44  48  52  56  60  64  68  72  76  80  84  88
  92  96 100]
Sum of doubled array: 1260
Reshaped array:
 [[20 24 28 32]
 [36 40 44 48]
 [52 56 60 64]
 [68 72 76 80]
 [84 88 92 96]]


In [26]:
print("Shape of reshaped array:", reshaped.shape)
print("Type of total:", type(total))


Shape of reshaped array: (5, 4)
Type of total: <class 'numpy.int64'>


In [27]:
try:
    from numpy_assignment_tests import test
    test.test_problem1(problem1)
except:
    print("Try Again!")

[✔] Problem 1 Passed — Score: 20/20



---

### ✅ **Problem 2: Indexing and Slicing**

**Steps to solve:**

1. Create a 5x5 NumPy array with numbers from 1 to 25 (row-wise).
2. Extract the 2nd and 4th rows (index 1 and 3).
3. Extract the 3rd column (index 2).
4. Extract a subarray from rows 2 to 4 and columns 2 to 5.

**Function Signature:**

In [29]:
def problem2():
    arr = np.arange(1, 26).reshape(5, 5)
    rows = arr[[1, 3], :]          
    col = arr[:, 2]               
    subarray = arr[2:5, 2:5]     

    return rows, col, subarray

problem2()

(array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]),
 array([ 3,  8, 13, 18, 23]),
 array([[13, 14, 15],
        [18, 19, 20],
        [23, 24, 25]]))

In [30]:
try:
    from numpy_assignment_tests import test
    test.test_problem2(problem2)
except:
    print("Try Again!")

[✔] Problem 2 Passed — Score: 20/20


---

### ✅ **Problem 3: Boolean Masking and Conditional Operations**

**Steps to solve:**

1. Create a NumPy array of integers from 1 to 20.
2. Use boolean masking to extract all numbers divisible by 3.
3. Replace all numbers greater than 15 in the original array with -1.

**Function Signature:**

In [31]:
import numpy as np

def problem3():
    # 1. Create a NumPy array of integers from 1 to 20
    arr = np.arange(1, 21)

    # 2. Use boolean masking to extract all numbers divisible by 3
    divisible_by_3 = arr[arr % 3 == 0]

    # 3. Replace all numbers greater than 15 in the original array with -1
    replaced_array = arr.copy()
    replaced_array[replaced_array > 15] = -1

    return divisible_by_3, replaced_array


In [32]:
div3, replaced = problem3()
print("Divisible by 3:", div3)
print("Replaced array:", replaced)


Divisible by 3: [ 3  6  9 12 15 18]
Replaced array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 -1 -1 -1 -1 -1]


In [33]:
try:
    from numpy_assignment_tests import test
    test.test_problem3(problem3)
except:
    print("Try Again!")

[✔] Problem 3 Passed — Score: 20/20


---

### ✅ **Problem 4: Aggregate Functions and Axis Operations**

**Steps to solve:**

1. Create a 4x4 NumPy array with values from 1 to 16.
2. Calculate the mean of each row.
3. Calculate the sum of each column.

**Function Signature:**

In [34]:
import numpy as np

def problem4():
    # 1. Create a 4x4 NumPy array with values from 1 to 16
    arr = np.arange(1, 17).reshape(4, 4)

    # 2. Calculate the mean of each row
    row_means = np.mean(arr, axis=1)

    # 3. Calculate the sum of each column
    col_sums = np.sum(arr, axis=0)

    return row_means, col_sums


In [35]:
row_means, col_sums = problem4()
print("Row Means:", row_means)
print("Column Sums:", col_sums)


Row Means: [ 2.5  6.5 10.5 14.5]
Column Sums: [28 32 36 40]


In [36]:
try:
    from numpy_assignment_tests import test
    test.test_problem4(problem4)
except:
    print("Try Again!")

[✔] Problem 4 Passed — Score: 20/20


---

### ✅ **Problem 5: Stacking and Splitting Arrays**

**Steps to solve:**

1. Create two NumPy arrays: `a = [1, 2, 3]`, `b = [4, 5, 6]`.
2. Stack them vertically and horizontally.
3. Split the horizontal stacked array into two equal parts.

**Function Signature:**

In [37]:
import numpy as np

def problem5():
    # 1. Create two NumPy arrays
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])

    # 2. Stack them vertically and horizontally
    vstacked = np.vstack((a, b))
    hstacked = np.hstack((a, b))

    # 3. Split the horizontal stacked array into two equal parts
    split_arrays = np.split(hstacked, 2)

    return vstacked, hstacked, split_arrays


In [38]:
v, h, splits = problem5()
print("Vertical Stack:\n", v)
print("Horizontal Stack:", h)
print("Split Arrays:", splits)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]
Split Arrays: [array([1, 2, 3]), array([4, 5, 6])]


In [39]:
try:
    from numpy_assignment_tests import test
    test.test_problem5(problem5)
except:
    print("Try Again!")

[✔] Problem 5 Passed — Score: 20/20


<h3><span style="color:red">🚨 Run the below cell to execute all test cases and get the final score</span></h3>


In [40]:
## DO NOT MODIFY ##
try:
    from numpy_assignment_tests import test
    student_name = input("Enter your full name: ").strip()
    test.run_all_tests({
        "problem1": problem1,
        "problem2": problem2,
        "problem3": problem3,
        "problem4": problem4,
        "problem5": problem5
    }, student_name)
except:
    print("Check again and complete all the questions completely!!")

=== NumPy Assignment Evaluation ===
[✔] Problem 1 Passed — Score: 20/20
[✔] Problem 2 Passed — Score: 20/20
[✔] Problem 3 Passed — Score: 20/20
[✔] Problem 4 Passed — Score: 20/20
[✔] Problem 5 Passed — Score: 20/20

🏁 Final Score: 100/100
